//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomoTimer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RomoTask
    {
        public int Id { get; set; }
        public string Task1 { get; set; }
        public string Task2 { get; set; }
        public string Task3 { get; set; }
        public string Task4 { get; set; }
        public string Task5 { get; set; }
        public string TotalTime { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public string UsernameOfCreator { get; set; }
    }
}
