//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomoTimer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public bool IsDarkTheme { get; set; }
        public Nullable<bool> IsBlueScheme { get; set; }
        public Nullable<bool> IsRedScheme { get; set; }
        public Nullable<bool> IsGreenScheme { get; set; }
        public Nullable<bool> IsOrangeScheme { get; set; }
    }
}
